export const SEARCH_RESULTS_FETCH = 'SEARCH_RESULTS_FETCH';
export const SEARCH_RESULTS_FETCH_SUCCESS = 'SEARCH_RESULTS_FETCH_SUCCESS';
export const SEARCH_RESULTS_FETCH_FAILURE = 'SEARCH_RESULTS_FETCH_FAILURE';

export const PREVIEW_RESULTS_FETCH = 'PREVIEW_RESULTS_FETCH';
export const PREVIEW_RESULTS_FETCH_SUCCESS = 'PREVIEW_RESULTS_FETCH_SUCCESS';
export const PREVIEW_RESULTS_FETCH_FAILURE = 'PREVIEW_RESULTS_FETCH_FAILURE';
export const PREVIEW_CLOSE = 'PREVIEW_CLOSE';

export const ANSWERS_FETCH = 'ANSWERS_FETCH';
export const ANSWERS_FETCH_SUCCESS = 'ANSWERS_FETCH_SUCCESS';
export const ANSWERS_FETCH_FAILURE = 'ANSWERS_FETCH_FAILURE';